---
- name: render agent config 
  template:
    src: config-agent.yaml.j2
    dest: "{{ k3s_config_dir }}/config.yaml"
    mode: '0644'

- name: render k3s agent system unit 
  template:
    src: k3s-agent.service.j2
    dest: "{{ k3s_systemd_dir }}/k3s-agent.service"
    mode: '0644'
  notify:
    - restart k3s-agent

- name: reload systemd 
  systemd:
    daemon_reload: true

- name: enable k3s  agent 
  systemd:
    name: k3s-agent
    enabled: true
    state: started