---
- name: create kubeconfig directory
  delegate_to: localhost
  file:
    path: "{{ k3s_kubeconfig_local_path }}"
    state: directory
    mode: '0755'

- name: fetch kubeconfig
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ k3s_kubeconfig_local_path }}/k3s.yaml"
    flat: true

- name: replace localhost with api endpoint
  delegate_to: localhost
  replace:
    path: "{{ k3s_kubeconfig_local_path }}/k3s.yaml"
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ k3s_api_endpoint }}:6443"