---
- name: Render k3s secondary server config
  template:
    src: config-server.yaml.j2
    dest: "{{ k3s_config_dir }}/config.yaml"
    mode: '0600'

- name: Render k3s systemd unit
  template:
    src: k3s.service.j2
    dest: "{{ k3s_systemd_dir }}/k3s.service"
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable secondary k3s
  systemd:
    name: k3s
    enabled: true
    state: started
  async: 120
  poll: 0